import { GpioPin } from "./types";

export const RPI_40_PINS: GpioPin[] = [
  { id: 1,  bcm: -1, name: "3.3V Power", defaultName: "3.3V DC", type: "power3v3", mode: "OUT", state: 1, isControllable: false, description: "3.3V Power Supply" },
  { id: 2,  bcm: -1, name: "5V Power", defaultName: "5.0V DC", type: "power5v", mode: "OUT", state: 1, isControllable: false, description: "5V Power Supply" },
  { id: 3,  bcm: 2,  name: "GPIO 2 (SDA)", defaultName: "GPIO 2", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "I2C1 Data" },
  { id: 4,  bcm: -1, name: "5V Power", defaultName: "5.0V DC", type: "power5v", mode: "OUT", state: 1, isControllable: false, description: "5V Power Supply" },
  { id: 5,  bcm: 3,  name: "GPIO 3 (SCL)", defaultName: "GPIO 3", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "I2C1 Clock" },
  { id: 6,  bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 7,  bcm: 4,  name: "GPIO 4", defaultName: "GPIO 4", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose / 1-Wire" },
  { id: 8,  bcm: 14, name: "GPIO 14 (TX)", defaultName: "GPIO 14", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "UART Transmit" },
  { id: 9,  bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 10, bcm: 15, name: "GPIO 15 (RX)", defaultName: "GPIO 15", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "UART Receive" },
  { id: 11, bcm: 17, name: "LED 1 (GPIO 17)", defaultName: "GPIO 17", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Pin 11 (Main LED 1)" },
  { id: 12, bcm: 18, name: "GPIO 18 (PWM)", defaultName: "GPIO 18", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Hardware PWM0" },
  { id: 13, bcm: 27, name: "LED 2 (GPIO 27)", defaultName: "GPIO 27", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Pin 13 (Main LED 2)" },
  { id: 14, bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 15, bcm: 22, name: "LED 3 (GPIO 22)", defaultName: "GPIO 22", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Pin 15 (Main LED 3)" },
  { id: 16, bcm: 23, name: "GPIO 23", defaultName: "GPIO 23", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose I/O" },
  { id: 17, bcm: -1, name: "3.3V Power", defaultName: "3.3V DC", type: "power3v3", mode: "OUT", state: 1, isControllable: false, description: "3.3V Power Supply" },
  { id: 18, bcm: 24, name: "Sensor (GPIO 24)", defaultName: "GPIO 24", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Pin 18 (Sensor Pin)" },
  { id: 19, bcm: 10, name: "GPIO 10 (MOSI)", defaultName: "GPIO 10", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "SPI0 Master Out" },
  { id: 20, bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 21, bcm: 9,  name: "GPIO 9 (MISO)", defaultName: "GPIO 9", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "SPI0 Master In" },
  { id: 22, bcm: 25, name: "GPIO 25", defaultName: "GPIO 25", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose I/O" },
  { id: 23, bcm: 11, name: "GPIO 11 (SCLK)", defaultName: "GPIO 11", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "SPI0 Clock" },
  { id: 24, bcm: 8,  name: "GPIO 8 (CE0)", defaultName: "GPIO 8", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "SPI0 Chip Enable 0" },
  { id: 25, bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 26, bcm: 7,  name: "GPIO 7 (CE1)", defaultName: "GPIO 7", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "SPI0 Chip Enable 1" },
  { id: 27, bcm: 0,  name: "ID_SD (EEPROM)", defaultName: "ID_SD", type: "id_eeprom", mode: "IN", state: 0, isControllable: false, description: "HAT ID I2C Data" },
  { id: 28, bcm: 1,  name: "ID_SC (EEPROM)", defaultName: "ID_SC", type: "id_eeprom", mode: "IN", state: 0, isControllable: false, description: "HAT ID I2C Clock" },
  { id: 29, bcm: 5,  name: "GPIO 5", defaultName: "GPIO 5", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose I/O" },
  { id: 30, bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 31, bcm: 6,  name: "GPIO 6", defaultName: "GPIO 6", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose I/O" },
  { id: 32, bcm: 12, name: "GPIO 12 (PWM)", defaultName: "GPIO 12", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Hardware PWM0" },
  { id: 33, bcm: 13, name: "GPIO 13 (PWM)", defaultName: "GPIO 13", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Hardware PWM1" },
  { id: 34, bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 35, bcm: 19, name: "GPIO 19 (PWM)", defaultName: "GPIO 19", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "Hardware PWM1 / PCM FS" },
  { id: 36, bcm: 16, name: "GPIO 16", defaultName: "GPIO 16", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose I/O" },
  { id: 37, bcm: 26, name: "GPIO 26", defaultName: "GPIO 26", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "General Purpose I/O" },
  { id: 38, bcm: 20, name: "GPIO 20", defaultName: "GPIO 20", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "PCM Audio Data In" },
  { id: 39, bcm: -1, name: "Ground", defaultName: "GND", type: "ground", mode: "IN", state: 0, isControllable: false, description: "0V Ground" },
  { id: 40, bcm: 21, name: "GPIO 21", defaultName: "GPIO 21", type: "gpio", mode: "OUT", state: 0, isControllable: true, description: "PCM Audio Data Out" }
];
